version: "3.7"

volumes:
  mariadb:
  backup:

services:
  mariadb:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql

  backup:
    build:
      context: ../../
      dockerfile: Dockerfile
      target: mariadb
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - TASK_database_CRONTAB="*/1 * * * *"
      - TASK_database_PREPARE="mkdir -p /mnt/backup/database"
      - TASK_database_EXTRACT="mysqldump --host=database --user=$MYSQL_USER --password=$MYSQL_PASSWORD $MYSQL_DATABASE > $SRC/database.backup.sql"
      - TASK_database_LOAD="duplicity $SRC file:///mnt/backup/database"
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql
        read_only: true
      - type: volume
        source: mariadb
        target: /mnt/backup
        read_only: false
