version: "3.7"

volumes:
  mariadb:
  backup:

services:
  mariadb:
    image: mariadb:10.4
    env_file:
      - database.env
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql

  duplicity:
    build:
      context: ../../
      dockerfile: Dockerfile.flavors
      target: mariadb
    links:
      - mariadb
    env_file:
      - database.env
      - backup.env
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql
        read_only: true
      - type: volume
        source: mariadb
        target: /mnt/backup
        read_only: false
