version: "3.7"

volumes:
  backup:

services:
  backup-test1:
    build:
      context: "../../"
      dockerfile: "Dockerfile.flavors"
      target: "cron"
    env_file:
      - test1.env
    volumes:
      - backup:/mnt/backup
  backup-test2:
    build:
      context: "../../"
      dockerfile: "Dockerfile.flavors"
      target: "cron"
    env_file:
      - test2.env
    volumes:
      - backup:/mnt/backup
  restore-test1:
    build:
      context: "../../"
      dockerfile: "Dockerfile.flavors"
      target: "cron"
    command: restore
    env_file:
      - test1.env
    volumes:
      - backup:/mnt/backup
